/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::realtime::models;
use serde::{Deserialize, Serialize};

/// TranscriptFilteringConfig : Configuration for filtering the transcript output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptFilteringConfig {
    /// When set to true, removes disfluencies (e.g., 'um', 'uh', 'er') from the transcript output.
    #[serde(rename = "remove_disfluencies", skip_serializing_if = "Option::is_none")]
    pub remove_disfluencies: Option<bool>,
}

impl TranscriptFilteringConfig {
    /// Configuration for filtering the transcript output.
    pub fn new() -> TranscriptFilteringConfig {
        TranscriptFilteringConfig {
            remove_disfluencies: None,
        }
    }
}

