/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

/// TranscriptionConfigTranscriptFilteringConfig : Configuration for filtering the transcript output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptionConfigTranscriptFilteringConfig {
    /// When set to true, removes disfluencies (e.g., 'um', 'uh', 'er') from the transcript output.
    #[serde(rename = "remove_disfluencies", skip_serializing_if = "Option::is_none")]
    pub remove_disfluencies: Option<bool>,
}

impl TranscriptionConfigTranscriptFilteringConfig {
    /// Configuration for filtering the transcript output.
    pub fn new() -> TranscriptionConfigTranscriptFilteringConfig {
        TranscriptionConfigTranscriptFilteringConfig {
            remove_disfluencies: None,
        }
    }
}

